MODEL:
  NUM_CLASSES: 2
  TYPE: generalized_rcnn
  CONV_BODY: FPN.fpn_ResNet50_conv5_body
  FASTER_RCNN: True
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 60000
  STEPS: [0, 30000, 40000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ASPECT_RATIOS : [1]
  RPN_MAX_LEVEL : 6
  RPN_MIN_LEVEL : 2
  RPN_ANCHOR_START_SIZE: 8
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  DATASETS: ('scuthead_a','scuthead_b','pascal_parts_heads',)
  SCALES: (1024,)
  MAX_SIZE: 1024
  BATCH_SIZE_PER_IM: 256
  RPN_MIN_SIZE : 8
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  SCALE: 1024
  MAX_SIZE: 1024
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
